# Generated by Django 5.2 on 2025-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.CharField(max_length=50)),
                ('source_ip', models.GenericIPAddressField()),
                ('description', models.TextField()),
            ],
        ),
    ]
