# Generated by Django 5.2 on 2025-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatalert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='threatalert',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='threatalert',
            name='attack_type',
        ),
        migrations.AddField(
            model_name='threatalert',
            name='alert_type',
            field=models.CharField(choices=[('DDOS', 'DDoS Attack'), ('PORT_SCAN', 'Port Scanning'), ('MITM', 'Man in the Middle'), ('BRUTE_FORCE', 'Brute Force')], default='DDOS', max_length=20),
        ),
        migrations.AddField(
            model_name='threatalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='threatalert',
            name='source_ip',
            field=models.CharField(max_length=45),
        ),
    ]
